version: '3.9'
services:
  django_todolist:
    container_name: django_todolist
    image: django_todolist:0.0.0
    build: .
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000 --timeout 120
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app/todolist_project
